{"uuid":"81897447-e047-403d-94bb-77d5a317e0ef","historyId":"705148a2e4f954cb2652d636ab7f92b5","fullName":"com.testingacademy.tests.vwoTests.TestVWOLogin_POM_Retry.testLoginNegativeVW2","labels":[{"name":"package","value":"com.testingacademy.tests.vwoTests.TestVWOLogin_POM_Retry"},{"name":"testClass","value":"com.testingacademy.tests.vwoTests.TestVWOLogin_POM_Retry"},{"name":"testMethod","value":"testLoginNegativeVW2"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"ATB7xWebAutomationFramework"},{"name":"subSuite","value":"com.testingacademy.tests.vwoTests.TestVWOLogin_POM_Retry"},{"name":"host","value":"DESKTOP-T2H52KL"},{"name":"thread","value":"18204@DESKTOP-T2H52KL.TestNG-test-ATB7xWebAutomationFramework-1(27)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Promode"}],"links":[],"name":"testLoginNegativeVW2","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [false] but found [true]","trace":"java.lang.AssertionError: expected [false] but found [true]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1067)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1031)\r\n\tat org.testng.Assert.assertEquals(Assert.java:1077)\r\n\tat com.testingacademy.tests.vwoTests.TestVWOLogin_POM_Retry.testLoginNegativeVW2(TestVWOLogin_POM_Retry.java:44)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)\r\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\r\n\tat org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\r\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\r\n"},"stage":"finished","description":"TC1 - Verify with the invalid login, error message is displayed.","steps":[],"attachments":[],"parameters":[],"start":1736952708678,"stop":1736952708717}